# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436756b67ddf7ce6511e5126b9e4d3bcd22b449e8f4b6dccfc235d28bb296b60be0f5d3a6a956208344cf11491e1a7cca1819f3d3fa54d63d5494124bb05f222

test:
  secret_key_base: dd851dfaf96131050c12d5a2ed56a2c10c28a5cfdc28e8f71b490d64a1bc0efd4ea3a4fcb3de25a3e034068d5f677e82eafd1f2748838116b0d3e1315c0656b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
